### ISSUE TITLE
Bad mysql bin location

### ISSUE THREAD

**Issue by chadrien** [occitech/capistrano-recipes#7]
Pretty sure this (https://github.com/occitech/capistrano-recipes/blob/master/BackupDatabase-Recipe.rb#L2)

``` ruby
_cset(:mysqldump_bin) { find_executable "mysqldump" }
```

will look for the location on the local env, not on the server.

A solution would be to to something like `run "which mysqldump"` or something

**Comment by adrien-louis-r** [comment]
Closed by cf42f726c9643187c8650664e1d94cfc4959e8c3
We now use `/usr/bin/env mysqldump`

**Comment by chadrien** [comment]
Seems to be working :+1:
